(require-builtin helix/core/keymaps as keymaps.)
(require (prefix-in cfg. "helix/configuration.scm"))

(define (key-values . key-values) (apply hash (apply append key-values)))

(define (normal->select value)
  (define command-map
    (key-values
      (list "select_mode" "exit_select_mode")
      (list "move_char_left" "extend_char_left")
      (list "move_visual_line_down" "extend_visual_line_down")
      (list "move_visual_line_up" "extend_visual_line_up")
      (list "move_char_right" "extend_char_right")
      (list "move_line_down" "extend_line_down")
      (list "move_line_up" "extend_line_up")
      (list "move_prev_long_word_start" "extend_prev_long_word_start")
      (list "move_next_long_word_start" "extend_next_long_word_start")
      (list "move_prev_long_word_end" "extend_prev_long_word_end")
      (list "move_next_long_word_end" "extend_next_long_word_end")
      (list "move_prev_sub_word_start" "extend_prev_sub_word_start")
      (list "move_next_sub_word_start" "extend_next_sub_word_start")
      (list "move_prev_sub_word_end" "extend_prev_sub_word_end")
      (list "move_next_sub_word_end" "extend_next_sub_word_end")
      (list "move_prev_word_start" "extend_prev_word_start")
      (list "move_next_word_start" "extend_next_word_start")
      (list "move_prev_word_end" "extend_prev_word_end")
      (list "move_next_word_end" "extend_next_word_end")
      (list "move_parent_node_start" "extend_parent_node_start")
      (list "move_parent_node_end" "extend_parent_node_end")
      (list "goto_first_nonwhitespace" "extend_to_first_nonwhitespace")
      (list "goto_file_start" "extend_to_file_start")
      (list "goto_file_end" "extend_to_file_end")
      (list "goto_line_end" "extend_to_line_end")
      (list "goto_last_line" "extend_to_last_line")
      (list "find_next_char" "extend_next_char")
      (list "find_prev_char" "extend_prev_char")
      (list "find_till_char" "extend_till_char")
      (list "till_prev_char" "extend_till_prev_char")
      (list "goto_word" "extend_to_word")
      (list "goto_line_start" "extend_to_line_start")
      (list "goto_line_end_newline" "extend_to_line_end_newline")
      (list "search_next" "extend_search_next")
      (list "search_prev" "extend_search_prev")
      (list "goto_column" "extend_to_column")))
  (define (transform-command str)
    (define new-value-or-false
      (hash-try-get command-map str))
    (if (not new-value-or-false)
      str
      new-value-or-false))
  (cond
    ((string? value)
      (transform-command value))
    ((list? value)
      (map transform-command value))
    ((hash? value)
      (transduce value
        (mapping (lambda (lst)
                  (define key (list-ref lst 0))
                  (define value (list-ref lst 1))
                  (list key (normal->select value))))
        (into-hashmap)))
    (else value)))

(define base-normal-mode
  (key-values
    (list "'"
      (key-values
        (list 'r "rename_symbol")
        (list 's "select_references_to_symbol_under_cursor")
        (list 'f "format_selections")
        (list 'ç "code_action")
        (list "\\" "signature_help")
        (list '/ "hover")))
    (list "\"" "select_register")
    (list "@" "record_macro")
    (list "#" "replay_macro")
    (list '% "select_all")
    (list '& "align_selections")
    (list '* "search_selection_detect_word_boundaries")
    (list 'C-* "search_selection")
    (list "(" "rotate_selections_backward")
    (list ")" "rotate_selections_forward")
    (list 'minus "decrement")
    (list '_ "trim_selections")
    (list '= "increment")
    (list '+
      (key-values
        (list 'i ":toggle-option lsp.display-inlay-hints")
        (list 'd ":toggle-option inline-diagnostics.cursor-line disable hint")
        (list 'x ":toggle-option soft-wrap.enable")
        (list 'm ":toggle-option auto-pairs")
        (list '> ":toggle-option indent-guides.render")
        (list '/ ":toggle-option search.smart-case")))
    (list 'tab
      (key-values
        (list 'q ":buffer-close")
        (list 'Q ":buffer-close!")
        (list 'w ":write")
        (list 'W ":write!")
        (list 'R ":reload")
        (list 't ":new")
        (list 'p "goto_previous_buffer")
        (list 's "goto_file")
        (list 'f ":format")
        (list 'n "goto_next_buffer")))
    (list 'q "move_prev_word_end")
    (list 'Q "move_prev_long_word_end")
    (list 'C-q "move_prev_sub_word_end")
    (list 'w "move_next_word_start")
    (list 'W "move_next_long_word_start")
    (list 'C-w "move_next_sub_word_start")
    (list 'e "move_next_word_end")
    (list 'E "move_next_long_word_end")
    (list 'C-e "move_next_sub_word_end")
    (list 'r "replace")
    (list 'R "replace_with_yanked")
    (list 'C-r
      (key-values
        (list 'minus "switch_to_lowercase")
        (list '= "switch_to_uppercase")
        (list 'b "switch_case")))
    (list 't "find_till_char")
    (list 'T "till_prev_char")
    (list 'y "yank")
    (list 'u "undo")
    (list 'U "redo")
    (list 'C-u "earlier")
    (list 'C-U "later")
    (list 'i "insert_mode")
    (list 'I "insert_at_line_start")
    (list 'o "open_below")
    (list 'O "open_above")
    (list 'p "paste_after")
    (list 'P "paste_before")
    (list "["
      (key-values
        (list 'e "goto_prev_entry")
        (list 't "goto_prev_class")
        (list 'T "goto_prev_test")
        (list 'p "goto_prev_paragraph")
        (list 'a "goto_prev_parameter")
        (list 'd "goto_prev_diag")
        (list 'D "goto_first_diag")
        (list 'f "goto_prev_function")
        (list 'g "goto_prev_change")
        (list 'G "goto_first_change")
        (list 'x "goto_prev_xml_element")
        (list 'c "goto_prev_comment")
        (list 'space "add_newline_above")))
    (list "]"
      (key-values
        (list 'e "goto_next_entry")
        (list 't "goto_next_class")
        (list 'T "goto_next_test")
        (list 'p "goto_next_paragraph")
        (list 'a "goto_next_parameter")
        (list 'd "goto_next_diag")
        (list 'D "goto_last_diag")
        (list 'f "goto_next_function")
        (list 'g "goto_next_change")
        (list 'G "goto_last_change")
        (list 'x "goto_next_xml_element")
        (list 'c "goto_next_comment")
        (list 'space "add_newline_below")))
    (list 'a "append_mode")
    (list 'A "insert_at_line_end")
    (list 's
      (key-values
        (list "(" "rotate_selection_contents_backward")
        (list ")" "rotate_selection_contents_forward")
        (list 'y "yank_joined")
        (list 'p "copy_selection_on_prev_line")
        (list 's "select_regex")
        (list 'j "join_selections")
        (list 'J "join_selections_space")
        (list 'k "keep_selections")
        (list 'K "remove_selections")
        (list 'x "split_selection_on_newline")
        (list 'b "reverse_selection_contents")
        (list 'n "copy_selection_on_next_line")
        (list 'm "merge_selections")
        (list 'M "merge_consecutive_selections")
        (list "," "remove_primary_selection")))
    (list 'S "split_selection")
    (list 'C-s
      (key-values
        (list 'i "shrink_selection")
        (list 'I "select_all_children")
        (list 'o "expand_selection")
        (list 'O "select_all_siblings")
        (list 'p "select_prev_sibling")
        (list 'P "move_parent_node_start")
        (list 'n "select_next_sibling")
        (list 'N "move_parent_node_end")))
    (list 'd "delete_selection_noyank")
    (list 'f "find_next_char")
    (list 'F "find_prev_char")
    (list 'g
      (key-values
        (list 'w "goto_word")
        (list 'r "goto_reference")
        (list 't "goto_type_definition")
        (list 'i "goto_implementation")
        (list 's "goto_window_center")
        (list 'd "goto_definition")
        (list 'D "goto_declaration")
        (list 'g "goto_file_start")
        (list 'h "goto_first_nonwhitespace")
        (list 'H "goto_line_start")
        (list 'j "move_line_down")
        (list 'J "goto_window_bottom")
        (list 'k "move_line_up")
        (list 'K "goto_window_top")
        (list 'l "goto_line_end")
        (list 'L "goto_line_end_newline")
        (list 'v "goto_column")
        (list "." "goto_last_modification")))
    (list 'G "goto_last_line")
    (list 'C-g
      (key-values
        (list 'C-g "save_selection")
        (list 'p "jump_backward")
        (list 'n "jump_forward")))
    (list 'h "move_char_left")
    (list 'j "move_visual_line_down")
    (list 'J (list "move_visual_line_down" "move_visual_line_down"))
    (list 'k "move_visual_line_up")
    (list 'K (list "move_visual_line_up" "move_visual_line_up"))
    (list 'l "move_char_right")
    (list 'ç "flip_selections")
    (list 'Ç "ensure_selections_forward")
    (list 'z
      (key-values
        (list 'j "scroll_down")
        (list 'J "align_view_top")
        (list 'k "scroll_up")
        (list 'K "align_view_bottom")
        (list 's "align_view_center")
        (list 'v "align_view_middle")))
    (list 'x "extend_line_below")
    (list 'X (list "extend_line_above"))
    (list 'C-x (list "ensure_selections_forward" "select_line_above"))
    (list 'C-X (list "ensure_selections_forward" "flip_selections" "select_line_below"))
    (list 'c "change_selection_noyank")
    (list 'C-c "toggle_comments")
    (list 'v "select_mode")
    (list 'b "move_prev_word_start")
    (list 'B "move_prev_long_word_start")
    (list 'C-b "move_prev_sub_word_start")
    (list 'n "search_next")
    (list 'N "search_prev")
    (list 'm
      (key-values
        (list 'q "@miW")
        (list 'w "@miw")
        (list 'e "@<C-e><S-e>e")
        (list 'r "surround_replace")
        (list 'i "select_textobject_inner")
        (list 'o "select_textobject_around")
        (list 'a "surround_add")
        (list 'd "surround_delete")
        (list 'h "extend_to_first_nonwhitespace")
        (list 'H "extend_to_line_start")
        (list 'l "extend_to_line_end")
        (list 'L "extend_to_line_end_newline")
        (list 'x "extend_to_line_bounds")
        (list 'X "shrink_to_line_bounds")
        (list 'm "match_brackets")
        (list "." "repeat_last_motion")))
    (list "," "keep_primary_selection")
    (list '< "unindent")
    (list '> "indent")
    (list ";" "collapse_selection")
    (list ': "command_mode")
    (list '/ "search")
    (list '? "rsearch")
    (list 'space
      (key-values
        (list 'tab "buffer_picker")
        (list 'e "file_explorer_in_current_directory")
        (list 'E "file_explorer")
        (list 'C-e "file_explorer_in_current_buffer_directory")
        (list 's "workspace_symbol_picker")
        (list 'S "symbol_picker")
        (list 'd "workspace_diagnostics_picker")
        (list 'D "diagnostics_picker")
        (list 'f "file_picker")
        (list 'F "file_picker_in_current_directory")
        (list 'C-f "file_picker_in_current_buffer_directory")
        (list 'g "changed_file_picker")
        (list 'C-g "jumplist_picker")
        (list 'z "suspend")
        (list ':
          (key-values
            (list 'o "@:open <C-r>%")
            (list 'g "@:cd <C-r>%")
            (list 'm "@:mv <C-r>%")))
        (list '/ "global_search")
        (list '? "command_palette")))
    (list 'left (list "move_char_left" "align_view_center" "align_view_middle"))
    (list 'down (list "move_visual_line_down" "align_view_center" "align_view_middle"))
    (list 'S-down (list "move_visual_line_down" "move_visual_line_down" "align_view_center" "align_view_middle"))
    (list 'up (list "move_visual_line_up" "align_view_center" "align_view_middle"))
    (list 'S-up (list "move_visual_line_up" "move_visual_line_up" "align_view_center" "align_view_middle"))
    (list 'right (list "move_char_right" "align_view_center" "align_view_middle"))
    (list 'ret
      (key-values
        (list 'q "wclose")
        (list 'ret "rotate_view")
        (list 'o "wonly")
        (list 's "hsplit")
        (list 'h "jump_view_left")
        (list 'H "swap_view_left")
        (list 'j "jump_view_down")
        (list 'J "swap_view_down")
        (list 'k "jump_view_up")
        (list 'K "swap_view_up")
        (list 'l "jump_view_right")
        (list 'L "swap_view_right")
        (list 'v "vsplit")))
    (list 'S-ret "rotate_view_reverse")))

(define normal-mode
  (hash-union base-normal-mode
    (key-values
      (list 'H (list "move_prev_sub_word_start" "collapse_selection"))
      (list 'L (list "move_next_sub_word_end" "collapse_selection"))
      (list 'S-left (list "move_prev_sub_word_start" "collapse_selection" "align_view_center" "align_view_middle"))
      (list 'S-right (list "move_next_sub_word_end" "collapse_selection" "align_view_center" "align_view_middle")))))

(define select-mode
  (hash-union
    (normal->select base-normal-mode)
    (key-values
      (list 'esc "normal_mode")
      (list 'H "extend_prev_sub_word_start")
      (list 'L "extend_next_sub_word_end")
      (list 'left (list "move_char_left" "align_view_center" "align_view_middle"))
      (list 'S-left (list "extend_prev_sub_word_start" "align_view_center" "align_view_middle"))
      (list 'down (list "extend_visual_line_down" "align_view_center" "align_view_middle"))
      (list 'S-down (list "extend_visual_line_down" "extend_visual_line_down" "align_view_center" "align_view_middle"))
      (list 'up (list "extend_visual_line_up" "align_view_center" "align_view_middle"))
      (list 'S-up (list "extend_visual_line_up" "extend_visual_line_up" "align_view_center" "align_view_middle"))
      (list 'right (list "extend_char_right" "align_view_center" "align_view_middle"))
      (list 'S-right (list "extend_next_sub_word_end" "align_view_center" "align_view_middle")))))

(define insert-mode
  (key-values
    (list 'esc "normal_mode")
    (list 'tab "smart_tab")
    (list 'S-tab "insert_tab")
    (list 'C-r "insert_register")
    (list 'C-u "commit_undo_checkpoint")
    (list 'C-d "delete_char_forward")
    (list 'C-D "delete_word_forward")
    (list "C-\\" "signature_help")
    (list 'C-x "completion")
    (list 'C-/ "hover")
    (list 'ret "insert_newline")
    (list 'S-ret "insert_newline")
    (list 'left (list "move_char_left" "align_view_center" "align_view_middle"))
    (list 'S-left (list "move_prev_sub_word_start" "collapse_selection" "align_view_center" "align_view_middle"))
    (list 'down (list "move_visual_line_down" "align_view_center" "align_view_middle"))
    (list 'S-down (list "move_visual_line_down" "move_visual_line_down" "align_view_center" "align_view_middle"))
    (list 'up (list "move_visual_line_up" "align_view_center" "align_view_middle"))
    (list 'S-up (list "move_visual_line_up" "move_visual_line_up" "align_view_center" "align_view_middle"))
    (list 'right (list "move_char_right" "align_view_center" "align_view_middle"))
    (list 'S-right (list "move_next_sub_word_end" "collapse_selection" "align_view_center" "align_view_middle"))
    (list 'backspace "delete_char_backward")
    (list 'S-backspace "delete_char_backward")))

(cfg.set-keybindings!
  (~> (hash 'normal normal-mode 'insert insert-mode 'select select-mode)
    (value->jsexpr-string)
    (keymaps.helix-string->keymap)))
