user-input-color: "#ced4e6"
tool-error-color: "#ea8f80"
tool-warning-color: "#c7a84d"
assistant-output-color: "#52bcce"
completion-menu-color: "#aeb8d4"
completion-menu-bg-color: "#1c2232"
completion-menu-current-color: "#f4dbe2"
completion-menu-current-bg-color: "#272d41"
code-theme: "nord-darker"
