name: Build & Push to Cachix

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build packages x86_64 Linux
        run: nix build -L .#nixosConfigurations.u.config.specialisation.attuned.configuration.boot.kernelPackages.kernel

      - name: Push outputs
        run: cachix push thou-vow ./result/*
