name: Bump and cache single package (manual dispatch)
on:
  workflow_dispatch:
    inputs:
      package:
        description: Derivation in legacyPackages (e.g. "x86_64-linux".attunedPackages.helix-steel)
        required: true
        type: string
      update_flake:
        description: Update flake before building?
        required: false
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - if: ${{ github.event.inputs.update_flake == 'true' }}
        run: |
          nix flake update
      - env:
          PACKAGE: ${{ github.event.inputs.package }}
        run: |
          cachix watch-exec -m xz -l 3 thou-vow -- \
            nix --accept-flake-config \
            build -L --impure --expr \
            "(builtins.getFlake (builtins.toString ./.)).legacyPackages.$PACKAGE"
