name: ⏰ Bump Binary Cache
on:
  schedule:
    - cron: '0 */18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock
        run: nix flake update --accept-flake-config

      - name: Build specific packages
        run: |
          nix build -L --accept-flake-config .#nixosConfigurations.u.config.specialisation.attuned.configuration.boot.kernelPackages.kernel

      - name: Push outputs to Cachix
        run: cachix push thou-vow ./result/*
