name: Bump and cache dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage
          nix-permission-edict: true

      - uses: canidae-solutions/lix-quick-install-action@v3
        with:
          lix_conf: |
            accept-flake-config = true
            always-allow-substitutes = true
            experimental-features = flakes nix-command pipe-operator

      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          gc-max-store-size-linux: 30G

      - run: |
          nix --extra-experimental-features "pipe-operator" build -L \
            .#nixosConfigurations.u.config.specialisation.attuned.configuration.system.build.toplevel \
            .#homeConfigurations.thou@u.config.specialisation.attuned.configuration.home.activationPackage

      - run: cachix push thou-vow ./result/*
