name: Bump and cache dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: |
          nix flake update

      - run: |
          nix --extra-experimental-features "flakes nix-command" --accept-flake-config \
            build -L --impure --expr \
            'let
              flake = builtins.getFlake (builtins.toString ./.);
            in
              flake.legacyPackages.x86_64-linux.attunedPackages'

      - run: cachix push thou-vow ./result/*
