name: Bump and cache dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage
          nix-permission-edict: true

      - uses: canidae-solutions/lix-quick-install-action@v3
        with:
          lix_conf: |

      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: |
          nix flake update

      - run: |
          nix --extra-experimental-features "flakes nix-command pipe-operator" --accept-flake-config build -L \
            .#nixosConfigurations.u.config.specialisation.attuned.configuration.system.build.toplevel \
            .#homeConfigurations.thou@u.config.specialisation.attuned.configuration.home.activationPackage

      - run: cachix push thou-vow ./result/*
