name: Bump dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock
        run: nix flake update --accept-flake-config

      - name: Build specific packages
        run: |
          nix build -L --accept-flake-config \
            .#nixosConfigurations.u.config.specialisation.attuned.configuration.boot.kernelPackages.kernel \
            .#homeConfigurations.thou@u.config.specialisation.attuned.configuration.mods.niri.package

      - name: Push to Cachix
        run: cachix push thou-vow ./result/*
