name: Bump and cache some packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */2 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          nix flake update
      - run: |
          cachix watch-exec -m xz -l 3 thou-vow -- \
            nix --accept-flake-config \
            build -L --impure --expr \
            'let
              packages = (builtins.getFlake (builtins.toString ./.)).legacyPackages;
            in
              (with packages."x86_64-linux"; [
                helix-steel
              ])
              ++ (with packages."x86_64-linux".attunedPackages; [
                cemu
                helix-steel
                linux-llvm
                niri-unstable
                rust-analyzer-unwrapped
                xwayland-satellite-unstable
              ])'
